# Generated by Django 5.0.1 on 2024-02-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookDetailsModel',
            fields=[
                ('detailsid', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bookmodel', verbose_name='Book Id')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField()),
                ('return_date', models.DateField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bookmodel', verbose_name='Book Id')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.usermodel', verbose_name='User Id')),
            ],
        ),
    ]
