# Generated by Django 5.0.1 on 2024-02-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_detailsid_bookdetailsmodel_details_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetailsmodel',
            old_name='details_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='bookid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='userid',
            new_name='id',
        ),
    ]
